// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/samuga-space/SpaceDashboard.tsx": () => import("../components/mockups/samuga-space/SpaceDashboard.tsx"),
  "./components/mockups/samuga-space/SpaceRepos.tsx": () => import("../components/mockups/samuga-space/SpaceRepos.tsx")
};
